apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hashed-network-ingress
  namespace: hashed-network
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - c1.hashed.network
    secretName: hashed-network-secret
  rules:
  - host: c1.hashed.network
    http:
      paths:
      - pathType: Prefix
        path: /p2p/
        backend:
          service:
            name: hashed-collator
            port:
              number: 40333
      - pathType: Prefix
        path: /rp2p/
        backend:
          service:
            name: hashed-collator
            port:
              number: 30333
      - pathType: Prefix
        path: /rws/
        backend:
          service:
            name: hashed-collator
            port:
              number: 9944
      - pathType: Prefix
        path: /ws/
        backend:
          service:
            name: hashed-collator
            port:
              number: 9946
      - pathType: Prefix
        path: /rpc/
        backend:
          service:
            name: hashed-collator
            port:
              number: 9933
      - pathType: Exact
        path: /
        backend:
          service:
            name: hashed-collator
            port:
              number: 9946
  