apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: hashed-collator-3-pdb
  namespace: hashed-network
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: hashed-collator-3
