apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: hashedcollator-persistentvolumeclaim
    namespace: hashed-network
spec:
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi