apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: hashed-network
spec:
  containers:
  - name: test-container
    image: ubuntu:20.04
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: "3"
        memory: "8G"
