[relaychain]
default_image = "docker.io/parity/polkadot:v1.3.0-1"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "docker.io/desneruda/hashed-test-collator"
  command = "hashed-parachain"
